Another way to get rid of shadows in an image
danmysak/print-clean pull request #1
Opened 2024-11-12 13:56 UTC by KourtKardash

Здравствуйте, Данило Петрович!

Я занимаюсь обработкой изображений, поэтому ваш репозиторий меня крайне заинтересовал. Хочу предложить вам свою реализацию этой библиотеки. Использования локального порога - отличный метод, но, на мой взгляд, в данной ситуации не очень подходит.
Я хочу предложить другой подход - сначала сильно размыть изображение Гауссом, а затем разделить исходное изображение на размытое. Тени и вариации освещения имеют низкочастотные компоненты. Детали самого изображения (в нашем случае - текст) являются высокочастотными компонентами. Размытие Гауссом с большим значением сигмы сглаживает изображение, сохраняя только медленно меняющиеся низкочастотные компоненты. Разделив исходное изображение на сглаженное, мы нормализуем низкочастотные компоненты, то есть получим чистый белый фон.
Так же я привела еще один пример (demo_2), на котором алгоритм, предложенный мной, сработает очень чисто, в то время как применение локального порога очень исказит сам текст.
Очень надеюсь на ваш ответ))

2024-11-13 13:22 UTC, danmysak commented
Добрий день, Світлано. Дякую за реалізацію альтернативного алгоритму. У вашому підході є плюси, є й невеликі мінуси (наприклад, залишковий сірий фон).

Чи не могли б ви змінити PR, залишивши користувачу можливість вибору, яким із двох алгоритмів користуватися?

2024-11-14 15:00 UTC, KourtKardash commented
Добрий день! Дякую, що звернули увагу на цей мінус моєго методу. Я додала ще один крок до алгоритму, який дозволяє почистити сірий фон, де він з'являєтся.
На ваше прохання додала ще один параметр (method), який відповідає за вибір методу: threshold - це ваш алгоритм, gauss_blur - мій.

2024-11-15 19:47 UTC, danmysak requested changes

2024-11-15 19:47 UTC, danmysak commented on src/printclean/perspective.py
> +    data = image_to_data(gray2rgb(image), lang=LANG_DELIMITER.join(languages), output_type=Output.DICT)
Із чим пов’язана ця зміна?

2024-11-15 19:47 UTC, danmysak commented on src/printclean/clean.py
> +def adjust_gamma(image, gamma=1.0):
Додайте типи.

2024-11-15 19:47 UTC, danmysak commented on src/printclean/clean.py
> +    parser_threshold.add_argument('images', nargs='+', help='Path to the image file(s).')
Винесіть зображення та мови із підпарсерів.

2024-11-15 19:47 UTC, danmysak commented on src/printclean/clean.py
> +    print('Done')
Поверніть перенесення рядка.

2024-11-15 19:47 UTC, danmysak commented on src/printclean/clean.py
> +
Винесіть, будь ласка, реалізацію кожного з двох алгоритмів у окрему функцію.

2024-11-16 07:42 UTC, KourtKardash commented on src/printclean/perspective.py
> +    data = image_to_data(gray2rgb(image), lang=LANG_DELIMITER.join(languages), output_type=Output.DICT)
Це пов'язано з тим, що після обробки зображення я відразу приводжу його до типу uint8. І до функції fix_perspective я передаю вже приведенне зображення. Тим самим я викликаю функцію перетворення до типу uint8 один раз, а не два. Вдруге вона викликалася у самому кінці при збереженні зображення.

2024-11-16 11:16 UTC, KourtKardash commented
Добрий день! Зараз є одна проблема з винесенням мов із підпарсерів. Потрібно, щоб можна було додати кілька мов. Але в цій ситуації все, що ми додаємо після мов, тобто підкоманди та їх параметри, сприйматимуться так само, як мови. Поки що я закоментувала nargs='+'. Якщо додати лише одну мову, все працює. Але як вирішити цю проблему, я поки не розумію. Чи не могли б ви мені допомогти?

2024-11-16 17:46 UTC, danmysak commented on src/printclean/clean.py
> +    return image
Чи код гарантовано коректно працюватиме, коли розміри зображення не діляться на WINDOW_SIZE?

2024-11-16 18:15 UTC, KourtKardash commented on src/printclean/clean.py
> +    return image
Так. NumPy дозволяє звертатися до зрізів масиву, і якщо діапазон перевищує розміри масиву, він автоматично обмежить його до меж зображення.

2024-11-18 16:14 UTC, danmysak commented on src/printclean/perspective.py
>      return rotate(image, slope_to_degrees(slope), resize=True, cval=1) if slope is not None else image
Чи тестували ви працездатність цієї функції після внесених змін (з обома методами)? У мене вона тепер не працює; на виході отримую чорний квадрат. Нашвидкуруч виправити це не вдалося.

2024-11-19 22:54 UTC, KourtKardash commented
Добрий день! Зараз все має бути добре. До речі, я вирішила проблему з винесенням мов та зображень з підпарсерів, про яку я писала раніше.

2024-11-20 05:41 UTC, danmysak commented
Дякую.
Дещо підправив у https://github.com/danmysak/print-clean/pull/1/commits/3f9f656d6d96ed9665e1b6c43b02e3b1980b375e. Якщо все гаразд, буду мерджити.

2024-11-20 10:03 UTC, KourtKardash commented
Ви встановили мій метод як дефолтий. Це мило, дякую!🥹

2024-11-20 10:09 UTC, KourtKardash commented on src/printclean/clean.py
>          help=f'The cleanup threshold, a value between 0 and {MAX_LEVEL} (larger is more aggressive).',
Можливо, тут також потрібно пояснити, що цей параметр необхідний для методу threshold?

2024-11-20 10:48 UTC, KourtKardash commented on src/printclean/clean.py
> +        '--method',
Можливо, все-таки варто рознести методи по різним субпарсерам?
По-перше, це читабельніше. У нас є два параметри, спільні для всіх методів (images та --lang). Якщо завтра з'являться кілька нових підходів, кожен з різным набором параметрів, буде наочніше створювати окремий субпарсер та конкретизувати набір параметрів для кожного методу.
По-друге, зараз користувач, задаючи метод gauss_blur, все одно може ввести параметр --level, який не має відношення до методу. Це не впливає на роботу, але все-таки це деяка невідповідність логіці.

2024-11-21 18:45 UTC, danmysak commented on src/printclean/clean.py
>          help=f'The cleanup threshold, a value between 0 and {MAX_LEVEL} (larger is more aggressive).',
Уточнив.

2024-11-21 18:47 UTC, danmysak commented on src/printclean/clean.py
> +        '--method',
У теорії згоден. На практиці конкретно зараз це зробить взаємодію користувача зі скриптом більш складною (замість простого запуску `printclean <path>` користувачу доведеться розбиратися з методами). Тому лишаю, як є.

2024-11-21 18:48 UTC, merged

2024-11-25 20:29 UTC, KourtKardash commented
Велике спасибі! Все, тепер я буду мріяти знову зустрітися з вами)) Ну і якщо будуть проекти з обробкою зображень, обов'язково пишіть!